services:
  mysql:
    image: mysql:8.0
    container_name: airline-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: airline
      MYSQL_USER: airline_user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - airline-network

volumes:
  mysql-data:

networks:
  airline-network:
